/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.Roupa;
import model.RoupaDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rafae  Esta classe segue o Princípio da Responsabilidade Única (SRP),
//                sendo responsável apenas pela interface gráfica do cadastro de roupas.
 */
public class FormRoupa extends javax.swing.JFrame {

    private Roupa roupa;
    private static FormRoupa cadRoupasUnico;
    
    
    /**
     * Creates new form FormRoupa
     */
    public FormRoupa() {
        initComponents();
        listarTab();
    }
    
    public static FormRoupa getRoupa(){
        if(cadRoupasUnico == null){
        cadRoupasUnico = new FormRoupa();
        }
        return cadRoupasUnico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEtiqueta = new javax.swing.JLabel();
        CampoId = new javax.swing.JTextField();
        lbCategoria = new javax.swing.JLabel();
        CampoNome = new javax.swing.JTextField();
        campoTamanho = new javax.swing.JTextField();
        lbModelo = new javax.swing.JLabel();
        lbCor = new javax.swing.JLabel();
        CampoCor = new javax.swing.JTextField();
        lbPreco = new javax.swing.JLabel();
        CampoPreco = new javax.swing.JTextField();
        lbDesconto = new javax.swing.JLabel();
        campoTipo = new javax.swing.JTextField();
        btRemover = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btLimpar1 = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btConsultar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbRoupas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbEtiqueta.setText("Informe o código da etiqueta:");

        lbCategoria.setText("Informe a nome:");

        CampoNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoNomeActionPerformed(evt);
            }
        });

        lbModelo.setText("Informe o tamanho: ");

        lbCor.setText("Informe a cor:");

        CampoCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoCorActionPerformed(evt);
            }
        });

        lbPreco.setText("Informe o preço:");

        lbDesconto.setText("Informe o tipo:");

        campoTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTipoActionPerformed(evt);
            }
        });

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        btLimpar1.setText("Limpar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        btConsultar.setText("Consultar");
        btConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsultarActionPerformed(evt);
            }
        });

        btAlterar.setText("Alterar");
        btAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarActionPerformed(evt);
            }
        });

        tbRoupas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "nome", "preço", "cor", "tamanho", "tipo"
            }
        ));
        jScrollPane1.setViewportView(tbRoupas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbCor, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoCor, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btAlterar)
                        .addGap(26, 26, 26)
                        .addComponent(btRemover)
                        .addGap(18, 18, 18)
                        .addComponent(btLimpar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEtiqueta)
                    .addComponent(CampoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCategoria)
                    .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPreco)
                    .addComponent(CampoPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTamanho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbModelo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCor)
                    .addComponent(CampoCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDesconto)
                    .addComponent(campoTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar1)
                    .addComponent(btCadastrar)
                    .addComponent(btConsultar)
                    .addComponent(btAlterar)
                    .addComponent(btRemover)
                    .addComponent(btSair))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoNomeActionPerformed

    private void CampoCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCorActionPerformed

    private void campoTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTipoActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        removerRoupa();
        listarTab();
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        sair();
    }//GEN-LAST:event_btSairActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        limpar();
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        cadastrarRoupa();
        listarTab();
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsultarActionPerformed
        consultarRoupa();
    }//GEN-LAST:event_btConsultarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        alterarRoupa();
        listarTab();
    }//GEN-LAST:event_btAlterarActionPerformed

    public void listarTab() {
   RoupaDAO dao = new RoupaDAO();
    List<Roupa> roupa = dao.listarRoupas();

    for (Roupa c : roupa) {
        System.out.println("ID: " + c.getId());
        System.out.println("Nome: " + c.getNome());
        System.out.println("Preco: " + c.getPreco());
        System.out.println("Tamanho: " + c.getTamanho());
        System.out.println("Cor: " + c.getCor());
        System.out.println("Tipo: " + c.getTipo());
        System.out.println("---------------");
    }
    
    DefaultTableModel modelo = (DefaultTableModel) tbRoupas.getModel();
        modelo.setRowCount(0); // limpa a tabela
        List<Roupa> lista = dao.listarRoupas();

        for (Roupa Roupa : lista) {
            modelo.addRow(new Object[]{
            Roupa.getId(),
            Roupa.getNome(),
            Roupa.getPreco(),
            Roupa.getCor(),
            Roupa.getTamanho(),
            Roupa.getTipo()
            });
        }
    }
    
    public void cadastrarRoupa() {
    int id = Integer.parseInt(CampoId.getText());
    String nome = CampoNome.getText();
    double preco = Double.parseDouble(CampoPreco.getText());
    String tamanho = campoTamanho.getText();
    String cor = CampoCor.getText();
    String tipo = campoTipo.getText();

    Roupa r = new Roupa(id, nome, preco, tamanho, cor, tipo);
    RoupaDAO dao = new RoupaDAO();
    dao.inserirRoupa(r);
    listarTab();
    limpar();
}
    
    public void alterarRoupa() {
    int id = Integer.parseInt(CampoId.getText());
    String nome = CampoNome.getText();
    double preco = Double.parseDouble(CampoPreco.getText());
    String tamanho = campoTamanho.getText();
    String cor = CampoCor.getText();
    String tipo = campoTipo.getText();

    Roupa r = new Roupa(id, nome, preco, tamanho, cor, tipo);
    RoupaDAO dao = new RoupaDAO();
    dao.atualizarRoupa(r);
    listarTab();
    limpar();
}
    
    public void consultarRoupa() {
    int id = Integer.parseInt(CampoId.getText());
    RoupaDAO dao = new RoupaDAO();
    Roupa r = dao.buscarRoupaPorId(id);
    if (r != null) {
        CampoNome.setText(r.getNome());
        CampoPreco.setText(String.valueOf(r.getPreco()));
        campoTamanho.setText(r.getTamanho());
        CampoCor.setText(r.getCor());
        campoTipo.setText(r.getTipo());
    } else {
        JOptionPane.showMessageDialog(null, "Roupa não encontrada!");
        limpar();
    }
}
    
    public void removerRoupa() {
    int id = Integer.parseInt(CampoId.getText());
    RoupaDAO dao = new RoupaDAO();
    dao.removerRoupaPorId(id);
    listarTab();
    limpar();
}
    
    public void limpar() {
    CampoId.setText("");
    CampoNome.setText("");
    CampoPreco.setText("");
    campoTamanho.setText("");
    CampoCor.setText("");
    campoTipo.setText("");
    CampoId.requestFocus();
}
    
    public void sair() {
    int resp = JOptionPane.showConfirmDialog(null, "Deseja Fechar o cadastro de Roupas?", "Saída", JOptionPane.YES_NO_OPTION);
    if (resp == 0) {
        this.dispose();
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormRoupa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormRoupa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoCor;
    private javax.swing.JTextField CampoId;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoPreco;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btConsultar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btSair;
    private javax.swing.JTextField campoTamanho;
    private javax.swing.JTextField campoTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCategoria;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbDesconto;
    private javax.swing.JLabel lbEtiqueta;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JTable tbRoupas;
    // End of variables declaration//GEN-END:variables
}
