package view;//IDE 23
//Nome: Rafael Tomé da Silva - RA:2623412;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author rafae
 */
public class FormCadastros extends javax.swing.JFrame {

    /**
     * Creates new form aaaaaaaaaaaaaaaa
     */
    public FormCadastros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        mnBarPrinc = new javax.swing.JMenuBar();
        mnCadastro = new javax.swing.JMenu();
        itMnCadCliente = new javax.swing.JMenuItem();
        itMnCadFuncionario = new javax.swing.JMenuItem();
        itMnCadRoupa = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnSair = new javax.swing.JMenu();
        itMnSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal");

        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Titulo.setText("Cadastros");

        mnCadastro.setText("Cadastro");

        itMnCadCliente.setText("Abrir Cadastro de Cliente");
        itMnCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadClienteActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadCliente);

        itMnCadFuncionario.setText("Abrir Cadastro de Funcionario");
        itMnCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadFuncionarioActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadFuncionario);

        itMnCadRoupa.setText("Abrir Cadastro de Roupa");
        itMnCadRoupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnCadRoupaActionPerformed(evt);
            }
        });
        mnCadastro.add(itMnCadRoupa);

        jMenuItem1.setText("Abrir Cadastro de Tenis");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnCadastro.add(jMenuItem1);

        mnBarPrinc.add(mnCadastro);

        mnSair.setText("Sair");

        itMnSair.setText("Fechar");
        itMnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itMnSairActionPerformed(evt);
            }
        });
        mnSair.add(itMnSair);

        mnBarPrinc.add(mnSair);

        setJMenuBar(mnBarPrinc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(Titulo)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(Titulo)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itMnCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadClienteActionPerformed
        FormCliente.getCliente().setVisible(true);
    }//GEN-LAST:event_itMnCadClienteActionPerformed

    private void itMnCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadFuncionarioActionPerformed
        FormFuncionario.getFuncionario().setVisible(true);
    }//GEN-LAST:event_itMnCadFuncionarioActionPerformed

    private void itMnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnSairActionPerformed
        sair();
    }//GEN-LAST:event_itMnSairActionPerformed

    private void itMnCadRoupaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itMnCadRoupaActionPerformed
        FormRoupa.getRoupa().setVisible(true);
    }//GEN-LAST:event_itMnCadRoupaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormTenis.getTenis().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    public void sair(){
        int resp = JOptionPane.showConfirmDialog(null, "Deseja Sair da Aplicacao?", "Saida", JOptionPane.YES_NO_OPTION);
            if(resp == 0){
                this.dispose();
            }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCadastros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Titulo;
    private javax.swing.JMenuItem itMnCadCliente;
    private javax.swing.JMenuItem itMnCadFuncionario;
    private javax.swing.JMenuItem itMnCadRoupa;
    private javax.swing.JMenuItem itMnSair;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar mnBarPrinc;
    private javax.swing.JMenu mnCadastro;
    private javax.swing.JMenu mnSair;
    // End of variables declaration//GEN-END:variables
}
